spring:
  datasource:
    url: jdbc:mysql://120.79.197.55:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: P@ssw0rd
    # 初始连接数
    initial-size: 10
    # 最大连接池数量
    max-active: 100
    # 最小连接池数量
    min-idle: 10
    # 配置获取连接等待超时的时间
    max-wait: 60000
#mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.hug.boot.api.model.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#shiro配置开始
shiro:
  #session配置
  session:
    sessionIdCookie:
      name: session-id
      path: /
      max-age: -1
    session-id-cookie-enabled: true
    session-id-url-rewriting-enabled: true
    global-session-timeout: 1800000
    session-cache-name: "shiro:session:"

  #realm配置
  realms:
  #realm类全路径
  - realm:
      target: org.apache.shiro.realm.jdbc.JdbcRealm
      property:
        cachingEnabled: true
        authenticationCachingEnabled: true
        authorizationCachingEnabled: true
        authenticationCacheName: usernamePasswordRealm2:authenticationCache
        authorizationCacheName: usernamePasswordRealm2:authorizationCache

      #凭证匹配器配置
      credentials-matcher:
        #凭证匹配器全路径
        target: org.apache.shiro.authc.credential.HashedCredentialsMatcher
        property:
          hashAlgorithmName: MD5
          hashIterations: 2
          storedCredentialsHexEncoded: true


  #记住我功能配置
  remember-me:
    cipher-key: this is ur cipher-key
    cookie:
      name: remember-me
      path: /
      max-age: 31536000

  #登录地址
  login-url: /login
  #登录成功默认跳转地址
  success-url: /index
  #无权限跳转地址
  unauthorized-url: /unauthorized
  #未登录响应状态码
  invalid-login-code: 418
  #未登录响应状态码
  invalid-permission-code: 401
  #定义系统是否只提供服务
  service-oriented: false
  #登录、登录失败、登出时返回的 json:{key：true/false}的key
  log-in-out-response-key: success
  #自定义filter配置
  filters:
    anon: org.apache.shiro.web.filter.authc.AnonymousFilter

  #自定义URL拦截器
  filter-chain-definitions:
    /** = anon